name: CI - Build & Push Docker images

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - name: backend
            context: backend
            dockerfile: backend/Dockerfile
            image: ${{ secrets.DOCKERHUB_USERNAME }}/emt-backend
          - name: frontend
            context: frontend
            dockerfile: frontend/Dockerfile
            image: ${{ secrets.DOCKERHUB_USERNAME }}/emt-frontend

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up QEMU (for buildx)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.service.context }}
          file: ${{ matrix.service.dockerfile }}
          push: true
          tags: |
            ${{ matrix.service.image }}:latest
            ${{ matrix.service.image }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
